package com.mytracksapp.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Status of a tracking session's lifecycle.
 *
 * Persisted by Room as TEXT (enum name) via Room's built-in enum type converter (Room 2.6+).
 * Downstream tasks (SessionController/T05, HistoryUI/T10, Export UI/T12) gate behavior on
 * whether a session is [FINISHED] ("encerrada" per SPEC.md UI-05/RF-08).
 */
enum class SessionStatus {
    ACTIVE,
    FINISHED,
}

/**
 * Room entity for a tracking session's metadata (RF-01, RF-04, RF-06, RF-07).
 *
 * [id] is a UUID string (decision recorded in PLAN.md T11/Assumptions, 2026-09-22): the CSV
 * export contract (CT-02, csv-export-schema.json) requires `session_id` to be a UUID string
 * matching this primary key's format, so the type is fixed here rather than left to an
 * autogenerated integer.
 *
 * [stoppedTimeMillis], [movingTimeMillis] and [averageSpeedMetersPerSecond] hold the final
 * metrics computed by StatsEngine (T07) and persisted once, on session end, per RF-07's
 * requirement that session metadata (interval, start/end time, stopped/moving time, average
 * speed) survive an app restart. Per-point classification (segment/moving-stopped, instant
 * speed) is intentionally NOT duplicated onto [com.mytracksapp.data.local.entity.GpsPointEntity]:
 * PLAN.md > Assumptions records that this is computed on demand from raw points by
 * StatsEngine/SegmentClassifier, not materialized per point.
 */
@Entity(tableName = "tracking_sessions")
data class TrackingSessionEntity(
    @PrimaryKey
    val id: String,
    val samplingIntervalSeconds: Int,
    val startTimestamp: Long,
    val endTimestamp: Long? = null,
    val status: SessionStatus = SessionStatus.ACTIVE,
    val stoppedTimeMillis: Long = 0L,
    val movingTimeMillis: Long = 0L,
    val averageSpeedMetersPerSecond: Double = 0.0,
    val locationName: String? = null,
    val distanceMeters: Double = 0.0,
)
